### ISSUE TITLE
gadget-cli fails when no ~/.ssh directory exists

### ISSUE THREAD

**Issue by claycooper** [NextThingCo/gadgetcli#1]
If no ~/.ssh directory exist, the gadget-cli will create one (even with a "help" argument) however it will give an error and not generate the needed key files.

```
$ gadget -v help
[0000] ERROR Couldn't determine if the default private key exists. error=stat /Users/<user>/.ssh/gadget_default_rsa: permission denied function=RequiredSsh keyLocation=/Users/<user>/.ssh/gadget_default_rsa
[0000] ERROR Failed to verify ssh requirements
```

```
$ ls -ld ~/.ssh
drw-r--r--  2 <user>  staff  68 Jul 18 21:43 /Users/<user>/.ssh
```

I believe this is because the permissions on a ~/.ssh directory should be 0700, not 0644 as configured at https://github.com/NextThingCo/gadgetcli/blob/testing/libgadget/infra.go#L161

OS: macOS 10.11.6
Gadget version: Alpha v0.4 (downloaded version, not locally compiled)
Shell: bash inside Terminal.app

**Comment by computermouth** [comment]
Confirmed and patched: https://github.com/NextThingCo/gadgetcli/commit/ebfbcbc9f65ac2f373f4b819f01bf974071afe92

Thanks!
